/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_davidecaroselli_jcld3_CLD3 */

#ifndef _Included_com_github_davidecaroselli_jcld3_CLD3
#define _Included_com_github_davidecaroselli_jcld3_CLD3
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_davidecaroselli_jcld3_CLD3_MAX_NUM_BYTES
#define com_github_davidecaroselli_jcld3_CLD3_MAX_NUM_BYTES 1000L
/*
 * Class:     com_github_davidecaroselli_jcld3_CLD3
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_davidecaroselli_jcld3_CLD3_init
  (JNIEnv *, jobject);

/*
 * Class:     com_github_davidecaroselli_jcld3_CLD3
 * Method:    findLanguage
 * Signature: (J[BLcom/github/davidecaroselli/jcld3/XLanguageResult;)V
 */
JNIEXPORT void JNICALL Java_com_github_davidecaroselli_jcld3_CLD3_findLanguage
  (JNIEnv *, jobject, jlong, jbyteArray, jobject);

/*
 * Class:     com_github_davidecaroselli_jcld3_CLD3
 * Method:    findTopNMostFreqLanguage
 * Signature: (J[B[Lcom/github/davidecaroselli/jcld3/XLanguageResult;)V
 */
JNIEXPORT void JNICALL Java_com_github_davidecaroselli_jcld3_CLD3_findTopNMostFreqLanguage
  (JNIEnv *, jobject, jlong, jbyteArray, jobjectArray);

/*
 * Class:     com_github_davidecaroselli_jcld3_CLD3
 * Method:    dispose
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_davidecaroselli_jcld3_CLD3_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
